AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Asserts NodeJS Lambda Layer
Parameters:
  LayerS3Key:
    Type: String
    Description: Layer S3 Key. For e.g. asserts-aws-lambda-layer-js-1.zip where `1` is the version of the layer
Resources:
  AssertsNodeJSAWSLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Description: >-
      Asserts AWS Lambda Layer for NodeJS Runtime that exports resource and invocation metrics in prometheus format
      to the API endpoint /api/v1/import/prometheus on a configured host
    Properties:
      LayerName: asserts-aws-lambda-layer-js
      CompatibleRuntimes:
        - nodejs14.x
      Content:
        S3Bucket: asserts-assets
        S3Key: !Ref LayerS3Key

