# Supported operations are 'add-layer', 'update-version', 'update-env-variables', 'disable', 'enable'
operation: add-layer

# Layer arn needs to be specified for 'add' or 'update-version' operations
layer_arn: arn:aws:lambda:us-west-2:689200961921:layer:asserts-aws-lambda-layer-js:4

# ASSERTS_METRIC_ENDPOINT is required for 'add' operation
ASSERTS_METRIC_ENDPOINT: https://chief.tsdb.dev.asserts.ai/api/v1/import/prometheus

# ASSERTS_TENANT and ASSERTS_PASSWORD are optional
ASSERTS_TENANT_NAME: chief
ASSERTS_PASSWORD: wrong
ASSERTS_ENVIRONMENT: dev
ASSERTS_SITE: dev

# OTEL Properties
ENABEL_TRACING=y
OTEL_LOG_LEVEL=DEBUG
OTEL_TRACES_SAMPLER=always_on
OTEL_EXPORTER_OTLP_ENDPOINT=Asserts-OTEL-Collector-Latest-1993150161.us-west-2.elb.amazonaws.com:4318

# Functions can be specified either through a regex pattern or through a list of function names
# function_name_pattern: Sample.+
function_names:
  - Sample-Function