Fix# Supported operations are 'add-layer', 'remove-layer', 'update-version', 'update-env-variables', 'disable-layer', 'enable-layer'
operation: disable-layer

# Layer arn needs to be specified for 'add' or 'update-version' operations
layer_arn: arn:aws:lambda:us-west-2:342994379019:layer:asserts-aws-lambda-layer-js:43

# ASSERTS_METRIC_ENDPOINT is required for 'add' operation
ASSERTS_METRIC_ENDPOINT: https://chief.tsdb.dev.asserts.ai/api/v1/import/prometheus

# ASSERTS_TENANT and ASSERTS_PASSWORD are optional
ASSERTS_TENANT_NAME: chief
ASSERTS_PASSWORD: wrong
ASSERTS_ENVIRONMENT: dev
ASSERTS_SITE: dev

# OTEL Properties
ENABEL_TRACING: y
OTEL_LOG_LEVEL: WARN
OTEL_TRACES_SAMPLER: always_on
OTEL_EXPORTER_OTLP_ENDPOINT: Asserts-OTEL-Collector-Latest-1213150131.us-west-2.elb.amazonaws.com:4318

# Functions can be specified either through a regex pattern or through a list of function names
# function_name_pattern: Sample.+
function_names:
  - BookRide